pipeline{
    agent any
    environment {
        PATH = "$PATH:/usr/share/maven"
    }
    stages{
        stage('Compile'){
            steps{
                sh 'mvn clean package'
            }
        }

        stage('image_build'){
            steps{
                sh '''
                    echo "buildinng image"
                    docker image build -t myapp ${WORKSPACE}/docker
                    '''
            }
        }

        stage('image_tagging'){
            steps{
                sh '''
                    echo "taggig image"
                    docker image tag myapp:latest rajeshaachari/myapp:latest
                    '''
            }
        }
        stage('image_push'){
            steps{
                sh '''
                    docker login -u rajeshaachari -p Rajesh@343
                    docker image push rajeshaachari/myapp:latest
                    '''
            }
        }
         stage('deploy'){
            steps{
                sh '''
                    echo "creating container..."
                    docker container run -d --name Server01 -p 9000:80 rajeshaachari/myapp:latest bash
                    '''
            }
        }
    }
}
